### ISSUE TITLE
请问能调整下JOY挂机的cron吗

### ISSUE THREAD

**Issue by HiJackXD** [shuye72/MyActions#10]
[作业执行时间 - 工作流程中的每个作业最多可以运行 6 个小时。 如果作业达到此限制，该作业将会终止而无法完成。](https://docs.github.com/cn/actions/reference/usage-limits-billing-and-administration#%E4%BD%BF%E7%94%A8%E9%99%90%E5%88%B6)
action默认单任务最多6小时的持续时间，所以JOY挂机能不能也调整成每6小时执行一次呢

**Comment by shuye72** [comment]
已调整，之前没注意

**Comment by HiJackXD** [comment]
> 已调整，之前没注意

谢谢，不过貌似修改成jd_crazy_joy.yaml了呀。应该是修改https://github.com/shuye72/MyActions/blob/main/.github/workflows/jd_crazy_joy_coin.yaml
才对哦

**Comment by shuye72** [comment]
哈哈 搞错了 谢谢提醒，jio本太多了没注意
