### ISSUE TITLE
可以更改东东超市兑换的物品，以及兑换物品的时间吗？

### ISSUE THREAD

**Issue by ZFeng3242** [shuye72/MyActions#13]
东东超市每晚准点有京豆和牛奶抵免券，挺香的
所以问问可不可以0.0

**Comment by shuye72** [comment]
github action无法准时唤醒，兑换类，直播抢豆类，劳烦请自备设备抢购，例如QX或者搭建docker

**Comment by ZFeng3242** [comment]
okk 十分感谢
