### ISSUE TITLE
时区的问题

### ISSUE THREAD

**Issue by tm306** [shuye72/MyActions#14]
有些定点才能参加的任务，在actions上要换算一下时间吧。搞不懂github上用的是哪个时区。

**Comment by shuye72** [comment]
UTC时间，action并不能强求定点任务，action通过cron设置的时间任务无法在某个具体的时间点唤醒，这个延迟有时候会延迟到2小时，有时候会延迟10分钟，所以任何需要抢购或者定点执行的任务还是自己准备设备执行相应的js脚本
