### ISSUE TITLE
互助码

### ISSUE THREAD

**Issue by biubiu10086** [shuye72/MyActions#19]
几个号一起互助的时候发现互助参数传入不了，在setting》secrets中定义的互助码
感觉是yml中没定义互助码参数，暂时发现没有传入互助的有压岁钱，神仙书院

**Comment by shuye72** [comment]
原来是这样，疏忽了。马上加进去

**Comment by shuye72** [comment]
已经好了，还有什么问题希望告诉我，谢谢了 ，这个确实我的锅

**Comment by biubiu10086** [comment]
没事没事，大佬辛苦，有问题会跟大佬讲的

**Comment by shuye72** [comment]
用不上互助码可能会引起比较大的误会，我会保持原作者的助力原则，所以这种事情还是比较严重的，谢谢你提出来
