### ISSUE TITLE
可以调一下jdfruit时间吗，qq

### ISSUE THREAD

**Issue by chanvvj** [shuye72/MyActions#2]
现在只有凌晨一次，助力奖励都没领，我自己改了时间，但是每天自动同步又被改回去了。qq

**Comment by shuye72** [comment]
抱歉 今天才看到 改为多久呢 给一个推荐的时间

**Comment by chanvvj** [comment]
> 抱歉今天才看到改造多久呢给一个推荐的时间

**Comment by chanvvj** [comment]
可以根据领水时间来，7-9  11-14  17-21
防止ac运行太多次被封，设置两次就可以了，少领一次影响不大
谢谢大大

**Comment by shuye72** [comment]
别别别 我就是搬运者 我尝试改一下，因为github是utc时间  而且github的唤醒存在延迟，并且延迟非常严重 不太好控制 我尝试一个最优的时间试试

**Comment by chanvvj** [comment]
> 别别别 我就是搬运者 我尝试改一下，因为github是utc时间 而且github的唤醒存在延迟，并且延迟非常严重 不太好控制 我尝试一个最优的时间试试

之前fork  lxk大佬的是  "0 0,5,9 * * *"这个时间
