### ISSUE TITLE
自动同步

### ISSUE THREAD

**Issue by dcthedo** [shuye72/MyActions#23]
大佬这个可以pull自动同步代码吗？我用你那个方法新建仓库，会同步那个lxk上gitew的代码吗？还是同步你这边的代码呢

**Comment by shuye72** [comment]
你可以同步lxk的，但是他的库无法跑action，我跟他的仓库目录结构不一样。至于怎么跑需要你自己研究了

**Comment by shuye72** [comment]
并且我目前的仓库不支持docker自动同步，无法使用QX后期等我设备到了会支持

**Comment by dcthedo** [comment]
好的👌感谢
