### ISSUE TITLE
求助

### ISSUE THREAD

**Issue by dcthedo** [shuye72/MyActions#25]
老哥出现这种咋办The log was not found. It may have been deleted based on retention settings.。。。。不管是fok还是reposync都是这种，是我cookie设置错了呢还是什么问题呢

**Comment by shuye72** [comment]
留下你的邮箱

**Comment by dcthedo** [comment]
好像没问题了。。。。

**Comment by dcthedo** [comment]
1393311099@qq.com

**Comment by shuye72** [comment]
还有麻烦取消 fork 谢谢

**Comment by shuye72** [comment]
注意查收邮件
