### ISSUE TITLE
shylocks脚本问题

### ISSUE THREAD

**Issue by aixiaolu** [shuye72/MyActions#4]
shylocks大佬在他的脚本都加入了禁止ac，删除这条就能用了
if(JSON.stringify(process.env).indexOf('GITHUB')>-1) process.exit(0)

**Comment by shuye72** [comment]
嗯 我发现了 今天刚看到这些问题 不过还是希望大家不要太高调 小心使用

**Comment by qingcher** [comment]
低调使用！
